### ISSUE TITLE
Narrow Window Loses Search Input Bar

### ISSUE THREAD

**Issue by noididntreadit** [thomaswangio/minimal-twitter#4]
@noididntreadit this commit addresses this issue! https://github.com/thomaswangio/minimal-twitter/commit/d3123ddad24fee3918a73c8a612d3e15d057b32b

Check back for the next update and it should be fixed :) thanks for pointing this out

_Originally posted by @thomaswangio in https://github.com/thomaswangio/minimal-twitter/issues/1#issuecomment-514118982_

Hi Thomas, I noticed today that I might have a secondary issue.

You mentioned that the search is in the top right, but it disappears in a thin enough window. I'm usually twittering on a vertical monitor (when I have multiple) or in side-by-side windows (when on a single screen), so the search is still obscured for me.

Also, do I need to do anything to get the updates? Do they push through chrome, or is it a manual process?

Thanks again!
Peter

**Comment by thomaswangio** [comment]
Oh man @noididntreadit I'm sorry, I resurfaced the search disappearing when I addressed another problem. Thanks for helping me out with this.

Fixed in this commit: https://github.com/thomaswangio/minimal-twitter/commit/7fd06955f4c61d530eb683292335dba966dd1681

**Comment by thomaswangio** [comment]
To get updates, the browsers are very manual, so no way to really get notified there.

But I'll be updating the releases on GitHub, so you can click Watch > Releases Only 

@noididntreadit

**Comment by noididntreadit** [comment]
Thank you for the quick cycles!

**Comment by fregante** [comment]
This is still broken for me

I see this code in Firefox Developer Tools

```css
      @media all and (max-width: 1400px) {
        form[aria-label="Search Twitter"][role="search"] {
          display: none !important;
        }
      }
      
```
